### ISSUE TITLE
Allow configuration of curl options

### ISSUE THREAD

**Issue by scott-r-lindsey** [8p/GuzzleBundle#109]
There is already a pull request on these lines (#103), but the tests are not updated and I couldn't find an docs to explain why one would want this, so I'll explain my reasons.

Red Hat Enterprise Linux makes a lot of strange choices; one of them in 6.7 is to backport newer versions of TLS, but to not use them unless you force them.  

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sec-Hardening_TLS_Configuration.html

> Some components in Red Hat Enterprise Linux are configured to use TLS 1.0 even though they provide support for TLS 1.1 or even 1.2. This is motivated by an attempt to achieve the highest level of interoperability with external services that may not support the latest versions of TLS. Depending on your interoperability requirements, enable the highest available version of TLS.

In any case, since it falls to the app guys to make curl work again, we can just pass through this argument.  

Unfortunately curl is configured through constants which are actually integers, and a config file full of integers is pretty ugly, so this probably also implies that arguments like "CURLOPT_SSLVERSION: 'CURL_SSLVERSION_TLSv1_2'" will need to be cleaned up in GuzzleBundle/DependencyInjection/GuzzleExtension.php

Is there an appetite for this feature, or is it just me?

**Comment by gregurco** [comment]
@scott-r-lindsey @florianpreusner I created new PR. So, how to create client with specific ssl version:
```yml
eight_points_guzzle:
    clients:
        api_payment:
            base_url: "https://google.com"

            options:
                curl:
                    sslversion: !php/const:CURL_HTTP_VERSION_1_0
```

Which options are allowed to use under `options.curl`? All options allowed in php and listed there: http://php.net/manual/en/function.curl-setopt.php .
How to use them? Just find proper php const, for example CURLOPT_FOLLOWLOCATION, remove _CURLOPT__ from the beginning and transform to lower case. Finally you will have next configfuration:
```yml
eight_points_guzzle:
    clients:
        api_payment:
            base_url: "https://google.com"

            options:
                curl:
                    followlocation: true
```

What do you think about this implementation? Any suggestions or remarks? It it's ok then I will add it to documentation and write some tests :)
