### ISSUE TITLE
Standar api call working with curl (console and php) but forbidden with Guzzle

### ISSUE THREAD

**Issue by compains** [8p/GuzzleBundle#130]
```
guzzle:
    clients:
        aws_lambda:
            base_url: "https://XXXXXXXX.amazonaws.com/prod"
            options:
                headers:
                    #Accept: "application/json"
                    User-Agent: 'custom agent'
                    x-api-key: 'somekey'
```

With this config when I use it I get 403 forbidden error. 

If I make the same request from console or with plain php curl, it works perfectly. I have tried to move the x-api-header to the controller and it's still failing.

Quite confused.
