### ISSUE TITLE
WSSE does not work

### ISSUE THREAD

**Issue by sebastianblum** [8p/GuzzleBundle#15]
hello Florian,

Thank you very much for your support, the last issue with the Content-Type-Header is working now.

At the moment, the wsse token is ignored, this is my configuration:

```
  guzzle:
    emarsys:
      base_url: %terrafinanz_email.export.uri%
      headers:
        'Content-Type': "application/json"
      plugin:
         wsse:
           username: %terrafinanz_email.export.username%
           password: %terrafinanz_email.export.secret%
```

In the console, I don't see the X-WSSE header:

![bildschirmfoto 2015-07-31 um 10 33 43](https://cloud.githubusercontent.com/assets/551751/9003607/a64930a2-376f-11e5-919e-f18878999593.png)

Thank you very much and greetings from munich, Sebastian
