### ISSUE TITLE
Request with cookie

### ISSUE THREAD

**Issue by sergiu-popa** [8p/GuzzleBundle#52]
Hello,

I'm trying to send a request with a cookie but it seems I can't quite figure it out:

```
$cookie = new SetCookie();
$cookie->setName('SESSIONID');
$cookie->setValue($token);
$cookie->setDomain('/');
$jar = new CookieJar();
$jar->setCookie($cookie);
```

`$response = $client->request('POST', 'path', ['form_params' => $send, 'cookies' => $jar]);`

Log:  Hostname x.x.x.x was found in DNS cache \* Trying x.x.x.x... \* Connected to x.x.x.x port 88 (#1) > POST /path HTTP/1.1 Host: x.x.x.x User-Agent: GuzzleHttp/6.2.0 curl/7.43.0 PHP/5.6.20 Content-Type: application/x-www-form-urlencoded Accept: application/json Content-Length: 156 \* upload completely sent off: 156 out of 156 bytes < HTTP/1.1 401 Unauthorized < Date: Thu, 23 Jun 2016 21:56:46 GMT < Server: NetTalk-WebServer/9.11 < Content-Length: 496 < Content-Type: text/html < Cache-Control: no-store, no-cache, must-revalidate, private,post-check=0, pre-check=0, max-age=0 < Pragma: no-cache < Connection: close < \* Closing connection 1

I can't find the cookie in the log. 
Also, `$client->getConfig` returns `'cookies' => boolean false`

I tried adding in config.yml the option `cookies: true` under my client, and also under options, but I get an error.

What am I doing wrong? Thanks

**Comment by florianpreusner** [comment]
I tested the behavior with your given data and everything seems to work correctly. That's why I'm closing this ticket.

Used following data/code:
```yaml
guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: true

    clients:
        test_client:
            base_url: "https://httpbin.org"

            # custom headers (@deprecated, will be removed in v6; new: "headers" in options (see below))
            headers:
                Accept: "application/json"

            # guzzle client options (full description here: https://guzzle.readthedocs.org/en/latest/request-options.html)
            # NOTE: "headers" option is not accepted here as it is provided as described above.
            options:
#                auth:
#                    - acme     # login
#                    - pa55w0rd # password

                headers:
                    Accept: "application/json"

                timeout: 30
```

```php
$cookie = new SetCookie();
$cookie->setName('SESSIONID');
$cookie->setValue('value123');
$cookie->setDomain('httpbin.org');
$jar = new CookieJar();
$jar->setCookie($cookie);

$client = $this->get('guzzle.client.test_client');
$response = $client->request('POST', 'post', ['form_params' => ['test' => 'true'], 'cookies' => $jar]);
```
