### ISSUE TITLE
Cannot set headers (results in 406 Not Acceptable response)

### ISSUE THREAD

**Issue by numediaweb** [8p/GuzzleBundle#77]
I'm using the bundle inside a service but cannot set the headers using settings:
_config.yml_:
```yml
# EightPoints GuzzleBundle
guzzle:
    clients:
        8p_guzzle_client:
            base_url: '%some_uri_1%'

        my_x_client:
            base_url: '%some_uri_2%'
            headers:
                Accept: 'application/json'
```

_services.yml_
```yml
services:
    crv.my_connect_api:
        class: AppBundle\My\MyConnect
        arguments:
            - "@guzzle.client.my_x_client"
```

_MyConnect.php_
```php
   public function __construct(GuzzleClient $client) {
        $this->client = $client;
    }
   public function login()
    {
        // Call the API
        $response = $this->client->get('/oauth/v2/token');
        dump($client); // client exists and is directing to corret URL
        dump($response); // Client error: `GET http:\/\/some-url.dev\/oauth\/v2\/token` resulted in a `406 Not Acceptable` response:\n\n\n \n \n
        die('It does not work :/');
    }
...

```
The strange thing is that my IDE (PhpStorm) does not detect the service `"@guzzle.client.my_x_client"` but detects `"@guzzle.client.8p_guzzle_client"` inside the _services.yml_
