### ISSUE TITLE
Query parameters from client configruation are missed on GET call with attributes

### ISSUE THREAD

**Issue by osavchenko** [8p/GuzzleBundle#93]
I have twi clients

```yaml
guzzle:
    clients:
        foo:
            base_url: "https://foo.com"
            options:
                query:
                    access_token: "%foo.page_access_token%"
        bar:
            base_url: "https://bar.com"
            options:
                query:
                    apikey: "%bar.consumerKey%"
```

With first client I make such requests:

```php
$this->getClient()->post('/foo', [
    'json' => $foo,
]);
```

And in this case I have appended query `access_token` to url like `https://foo.com/foo?access_token=some_token`.

And with second client I make such requests:

```php
$this->getClient()->get('/bar', [
    'query' => [
        'bar' => $this->getBar(),
    ],
])
```

And in this case my query `apikey` is missing here.

Is it a bug or I use current bundle in incorrect way?
